[tool.poetry]
name = "ospeople"
version = "2.0"
description = ""
authors = ["James Turk <james@openstates.org>"]

[tool.poetry.dependencies]
python = "^3.9"
yamlordereddictloader = "^0.4.0"
Django = "^3.2"
scrapelib = "^2.0"
openstates = "^6.0.0"
spatula = "^0.6.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
pytest = "^5.1"
pytest-django = "^3.5"
pytest-cov = "^2.7"
coveralls = "^1.8"
invoke = "^1.5.0"
mypy = "^0.812"

[tool.black]
line-length = 99
target-version = ["py37"]
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

