ma:
  vacancies:
  - chamber: lower
    district: '6th Worcester'
    vacant_until: 2024-04-01
mo:
  vacancies:
  - chamber: lower
    district: 78
    vacant_until: 2025-01-01
sc:
  vacancies:
  - chamber: lower
    district: '109'
    vacant_until: 2025-01-01
