ct:
  vacancies:
  - chamber: lower
    district: 112
    vacant_until: 2021-07-01
al:
  vacancies:
  - chamber: upper
    district: 14
    vacant_until: 2021-07-13
  - chamber: upper
    district: 26
    vacant_until: 2021-03-21
ca:
  vacancies:
  - chamber: upper
    district: 30
    vacant_until: 2021-06-01
  - chamber: lower
    district: '79'
    vacant_until: 2021-05-08
ga:
  vacancies:
  - chamber: lower
    district: 90
    vacant_until: 2021-03-21
mo:
  vacancies:
  - chamber: lower
    district: 45
    vacant_until: 2021-04-01
me:
  vacancies:
  - chamber: upper
    district: 14
    vacant_until: 2021-03-21
nh:
  vacancies:
  - chamber: lower
    district: Hillsborough 21
    vacant_until: 2021-06-01
  - chamber: lower
    district: Rockingham 6
    vacant_until: 2021-06-01
pa:
  vacancies:
  - chamber: upper
    district: 48
    vacant_until: 2021-05-18
parties:
- Democratic
- Green
- Independent
- Libertarian
- Nonpartisan
- Progressive
- Republican
- Democratic-Farmer-Labor
- Democratic/Progressive
- Progressive/Democratic
- Republican/Democratic
- Carter County Republican
- Independence
- "Partido Independentista Puertorrique\xF1o"
- Partido Nuevo Progresista
- "Partido Popular Democr\xE1tico"
- Proyecto Dignidad
- Movimiento Victoria Ciudadana
ma:
  vacancies:
  - chamber: lower
    district: 19th Suffolk
    vacant_until: 2021-04-23
wi:
  vacancies:
  - chamber: lower
    district: '89'
    vacant_until: 2021-04-24
  - chamber: upper
    district: '13'
    vacant_until: 2021-04-24
la:
  vacancies:
  - chamber: lower
    district: 82
    vacant_until: 2021-04-01
