al:
  vacancies:
  - chamber: lower
    district: 29
    vacant_until: 2023-03-06
  - chamber: lower
    district: 47
    vacant_until: 2023-03-06
ct:
  vacancies:
  - chamber: lower
    district: 100
    vacant_until: 2025-01-08
fl:
  vacancies:
  - chamber: lower
    district: '50'
    vacant_until: 2023-03-06
  - chamber: lower
    district: '11'
    vacant_until: 2023-03-06
  - chamber: upper
    district: '36'
    vacant_until: 2023-03-06
la:
  vacancies:
  - chamber: upper
    district: '5'
    vacant_until: 2023-04-09
us:
  vacancies:
    - chamber: lower
      district: 'FL-22'
      vacant_until: 2022-12-30
