hi:
  vacancies:
  - chamber: lower
    district: '10'
    vacant_until: 2025-01-10
ma:
  vacancies:
  - chamber: lower
    district: '6th Worcester'
    vacant_until: 2024-04-01
sc:
  vacancies:
  - chamber: lower
    district: '109'
    vacant_until: 2025-01-01
