az:
  vacancies:
  - chamber: lower
    district: 26
    vacant_until: 2025-01-08
in:
  vacancies:
  - chamber: lower
    district: '31'
    vacant_until: 2025-01-10
me:
  vacancies:
  - chamber: lower
    district: '45'
    vacant_until: 2025-01-10
wi:
  vacancies:
  - chamber: lower
    district: '24'
    vacant_until: 2025-01-01
