az:
  vacancies:
  - chamber: lower
    district: 26
    vacant_until: 2025-01-08
ga:
  vacancies:
  - chamber: lower
    district: '119'
    vacant_until: 2025-01-08
ky:
  vacancies:
  - chamber: upper
    district: '28'
    vacant_until: 2023-05-17
md:
  vacancies:
  - chamber: upper
    district: '16'
    vacant_until: 2025-01-08
vt:
  vacancies:
    - chamber: lower
      district: Lamoille-2
      vacant_until: 2025-01-08
wi:
  vacancies:
  - chamber: upper
    district: '8'
    vacant_until: 2023-05-19
