az:
  vacancies:
  - chamber: lower
    district: 26
    vacant_until: 2025-01-08
in:
  vacancies:
  - chamber: lower
    district: '31'
    vacant_until: 2025-01-10
me:
  vacancies:
  - chamber: lower
    district: '45'
    vacant_until: 2025-01-10
ky:
  vacancies:
  - chamber: upper
    district: '28'
    vacant_until: 2023-06-30
wi:
  vacancies:
  - chamber: lower
    district: '24'
    vacant_until: 2025-01-01
