hi:
  vacancies:
  - chamber: lower
    district: '10'
    vacant_until: 2025-01-10
in:
  vacancies:
  - chamber: lower
    district: '31'
    vacant_until: 2025-01-10
sc:
  vacancies:
  - chamber: lower
    district: '109'
    vacant_until: 2025-01-01
wi:
  vacancies:
  - chamber: lower
    district: '24'
    vacant_until: 2025-01-01
