ct:
  vacancies:
  - chamber: lower
    district: 112
    vacant_until: 2021-07-01
al:
  vacancies:
  - chamber: upper
    district: 14
    vacant_until: 2021-07-15
  - chamber: lower
    district: 78
    vacant_until: 2021-07-15
  - chamber: lower
    district: 73
    vacant_until: 2021-07-15
ca:
  vacancies:
  - chamber: upper
    district: 30
    vacant_until: 2021-06-01
nh:
  vacancies:
  - chamber: lower
    district: Hillsborough 21
    vacant_until: 2021-06-01
  - chamber: lower
    district: Rockingham 6
    vacant_until: 2021-06-01
pa:
  vacancies:
  - chamber: upper
    district: 48
    vacant_until: 2021-05-18
parties:
- Democratic
- Green
- Independent
- Libertarian
- Nonpartisan
- Progressive
- Republican
- Democratic-Farmer-Labor
- Democratic/Progressive
- Progressive/Democratic
- Republican/Democratic
- Carter County Republican
- Independence
- "Partido Independentista Puertorrique\xF1o"
- Partido Nuevo Progresista
- "Partido Popular Democr\xE1tico"
- Proyecto Dignidad
- Movimiento Victoria Ciudadana
wi:
  vacancies:
  - chamber: lower
    district: 89
    vacant_until: 2021-06-01
  - chamber: lower
    district: 37
    vacant_until: 2021-06-01
us:
  vacancies:
  - chamber: lower
    district: FL-20
    vacant_until: 2021-07-01
  - chamber: lower
    district: NM-1
    vacant_until: 2021-07-01
  - chamber: lower
    district: OH-11
    vacant_until: 2021-07-01
  - chamber: lower
    district: TX-6
    vacant_until: 2021-07-01
  - chamber: lower
    district: LA-2
    vacant_until: 2021-07-01
