az:
  vacancies:
  - chamber: lower
    district: 5
    vacant_until: 2025-01-01
  - chamber: lower
    district: 8
    vacant_until: 2025-01-01
ma:
  vacancies:
  - chamber: lower
    district: '6th Worcester'
    vacant_until: 2024-04-01
mi:
  vacancies:
  - chamber: lower
    district: 13
    vacant_until: 2025-01-01
  - chamber: lower
    district: 25
    vacant_until: 2025-01-01
me:
  vacancies:
  - chamber: lower
    district: 122
    vacant_until: 2024-04-06
mo:
  vacancies:
  - chamber: lower
    district: 78
    vacant_until: 2025-01-01
nh:
  vacancies:
  - chamber: lower
    district: Rockingham 21
    vacant_until: 2024-03-13
  - chamber: lower
    district: Strafford 11
    vacant_until: 2024-03-13
ny:
  vacancies:
  - chamber: lower
    district: '77'
    vacant_until: 2024-02-14
oh:
  vacancies:
  - chamber: lower
    district: 32
    vacant_until: 2025-01-01
  - chamber: lower
    district: 33
    vacant_until: 2025-01-01
pa:
  vacancies:
  - chamber: lower
    district: 140
    vacant_until: 2025-01-01
pr:
  vacancies:
  - chamber: lower
    district: 29
    vacant_until: 2025-01-01
sc:
  vacancies:
  - chamber: lower
    district: '109'
    vacant_until: 2025-01-01
