al:
  vacancies:
  - chamber: lower
    district: 78
    vacant_until: 2021-08-01
  - chamber: lower
    district: 73
    vacant_until: 2021-08-01
wi:
  vacancies:
  - chamber: lower
    district: 37
    vacant_until: 2021-08-14
us:
  vacancies:
  - chamber: lower
    district: FL-20
    vacant_until: 2022-01-12
  - chamber: lower
    district: OH-11
    vacant_until: 2021-11-03
  - chamber: lower
    district: TX-6
    vacant_until: 2021-07-28
